### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by black-wt** [silencesys/silentbox#1]
$option is not defined

**Comment by hustleandcuss** [comment]
+1

**Comment by silencesys** [comment]
In which scenario is $option undefined? I wasn't able to get this error.

**Comment by hustleandcuss** [comment]
I realised that I got an old version from npm but when I specify v.0.1.0, I get no such error. :)
Although notised another issue now, for the first picture in the a group you have to press the arrow twice for it to change picture, it is the same way at the demo page, not only my application.

**Comment by silencesys** [comment]
Ok, I'm closing it then. :)

**Comment by black-wt** [comment]
How to  specify v.0.1.0?

**Comment by hustleandcuss** [comment]
I just changes the version in package.json
