### ISSUE TITLE
Improperly Packaged for NPM

### ISSUE THREAD

**Issue by DanielStout5** [silencesys/silentbox#10]
This library looks great, but the fact the NPM package includes SASS and .vue files is not standard practice.

It means the library can't be used directly in the browser, and it means the user is required to ensure `vue-loader` includes `node_modules` (to translate the .vue files) and that their own project uses `node-sass` and `sass-loader`.

Here's the recommended best practice:

https://vuejs.org/v2/cookbook/packaging-sfc-for-npm.html#Can%E2%80%99t-I-Just-Share-vue-Files-Directly

**Comment by silencesys** [comment]
Thank you for the notice and an advice, the package should be repackaged and no longer requiring other modules.
