### ISSUE TITLE
Render local video file

### ISSUE THREAD

**Issue by johnnymetz** [silencesys/silentbox#17]
Is there anyway to render a local video. I'm working with mp4 files. I would imagine this should work but it isn't:

    <silentbox-item src="location/to/file.mp4">

I'm using the nuxt framework and have even tried serving the videos as [static files](https://nuxtjs.org/guide/assets/#static):

    <silentbox-item src="/file.mp4">
    <silentbox-item src="http://localhost:3000/file.mp4">

Am I doing anything wrong or is this not built in to the library?

**Comment by egs2003** [comment]
I have the same problem. Is there any solution here in the meantime?

**Comment by silencesys** [comment]
SilentBox2 should be able to do that.
