### ISSUE TITLE
Documentation on end tags

### ISSUE THREAD

**Issue by godbrain** [silencesys/silentbox#24]
I don't think you updated the end tags from version 1...
I was a bit confused on this. (- single) should be removed from the end tags

Thanks

Then in the template you use a silent-box component to display the gallery.

`<silent-box :gallery="images"></silentbox-single>
<silent-box :image="images[0]"></silentbox-single>`

**Comment by silencesys** [comment]
Thank you for reporting, readme should be updated now.
