### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by jsaidler** [silencesys/silentbox#27]
Hi! Amazing plugin! Many thanks for developing it!

On my https site the videos on youtube don't load and i get a black screen with this error on console:

Mixed Content: The page at 'https://jsaidlerfotografia.com.br/' was loaded over HTTPS, but requested an insecure frame 'http://www.youtube.com/embed/ygVTaeRNiqk?rel=0'. This request has been blocked; the content must be served over HTTPS.

```

<silent-box :gallery="images"></silent-box>

data: function () {
    return {
      images: [
        { src: 'https://www.youtube.com/watch?v=ygVTaeRNiqk', thumbnailWidth: '100px' },
        { src: 'https://www.youtube.com/watch?v=Ip8Y8SZWmOY', thumbnailWidth: '100px' },
        { src: 'https://www.youtube.com/watch?v=WZRbzuWvq1g', thumbnailWidth: '100px' },
        { src: 'https://www.youtube.com/watch?v=9rxCH85eWxg', thumbnailWidth: '100px' },
        { src: 'https://www.youtube.com/watch?v=0GF4WuPZ2Q4', thumbnailWidth: '100px' }
      ]
    }
```

Version:

 "_id": "vue-silentbox@2.0.1",

**Comment by jsaidler** [comment]
Found this on the code on my dist folder:
`
                parseYoutubeVideo(t) {
                    let e = "";
                    const n = this.getYoutubeVideoId(t);
                    return n && (e = "http://www.youtube.com/embed/" + n + "?rel=0",
                    "autoplay" === this.overlayItem.autoplay && (e += "&autoplay=1"),
                    this.overlayItem.controls || (e += "&controls=0")),
                    e
                },`

Looking on vue-silentbox , I have found this http:// code only on dist folder.

**Comment by silencesys** [comment]
Hi, thank you for reporting it, I'll update the silentbox over the weekend.

**Comment by silencesys** [comment]
Should be fixed now, but let me know if not. :)
