### ISSUE TITLE
thumbnailHeight does not maintain aspect ratio

### ISSUE THREAD

**Issue by lukasvida** [silencesys/silentbox#28]
Hi, 
when I use `thumbnailWidth`, the resulting `<img>` tag gets specified width and `height=auto`, but when I use `thumbnailHeight`, both height and width are set to that specified value. 
Shouldn't thumbnailHeight preserve aspect ratio too?

**Comment by silencesys** [comment]
Hello, thank you for reporting the issue, it should be fixed in version 2.1.x. 🙂
