### ISSUE TITLE
Arrows are not displayed

### ISSUE THREAD

**Issue by cfab** [silencesys/silentbox#29]
Next and previous arrows are not displayed, but keyboard navigation is working. 
I'm using silentbox with latest nuxt (2.13)  and plugin is set in client mode. Everything is perfect besides this.

**Comment by silencesys** [comment]
Which browser do you use?

**Comment by cfab** [comment]
Chrome, firefox, safari… Latest for Mac (Catalina)

**Comment by cfab** [comment]
Btw, there is no rendered div with the class of "silentbox-overlay__arrow-buttons" for the arrows as in your demo on https://silentbox.silencesys.com/

**Comment by silencesys** [comment]
Thank you for reporting the issue, arrows should be fixed. 🙂

**Comment by cfab** [comment]
Yes ! Thank you very much !
