### ISSUE TITLE
First picture in group doesn't seem to act as expected

### ISSUE THREAD

**Issue by hustleandcuss** [silencesys/silentbox#3]
Notised another issue now, for the first picture in the a group you have to press the arrow twice for it to change picture, it is the same way at the demo page, not in my application.

**Comment by silencesys** [comment]
Thanks, I've also noticed that, I'll look at it during the weekend. :)

**Comment by silencesys** [comment]
It should be fixed in a2c2a0520e4e1b92275e771af844bc2525780189.

**Comment by hustleandcuss** [comment]
Nice :)
