### ISSUE TITLE
lazy loading ?

### ISSUE THREAD

**Issue by cfab** [silencesys/silentbox#32]
Hello, not sure how it works but apparently quite a few modern browsers support loding:lazy now. 
I've checked the generated html by default and saw that this attribute is not present. Is there a way to add it ?
Or maybe you could add it by default ?

**Comment by JohnyProkie** [comment]
Incorporated to PR https://github.com/silencesys/silentbox/pull/44

**Comment by silencesys** [comment]
Thanks @JohnyProkie for implementation. See [documentation](https://github.com/silencesys/silentbox#gallery-element-attributes) how to use it.
