### ISSUE TITLE
Add download button.

### ISSUE THREAD

**Issue by uwejan** [silencesys/silentbox#36]
Am still trying to figure out a way once the image clicked make a download button available on the top right, or left.
apparently there is not props for that.
Am open for suggestions please.

**Comment by GuillaumeSTEIN** [comment]
Would be much appreciated here too :-)
Thanks

**Comment by silencesys** [comment]
Download option was added, not sure about the extendability as I'm not sure where to start. :)

**Comment by vkyeswa** [comment]
> Download option was added, not sure about the extendability as I'm not sure where to start. :)

Hi @silencesys you could provide a slot for tool-buttons in the #silentbox-overlay__tool-buttons div
