### ISSUE TITLE
Open SilentBox without html activator?

### ISSUE THREAD

**Issue by truongleit** [silencesys/silentbox#37]
Hello, I would like to ask a question concerning this splendid Vue package. I am using the Vue SilentBox for a preview-image section for my application. Based on my UI design, whenever user clicks on the button listed in the table, SilentBox will be opened, hence, I need to hide  this part `<silent-box :gallery="images"><!-- your additional content --></silent-box>` by forcing CSS style. My question is how can open the SilentBox without displaying the original html activator? @silencesys

**Comment by silencesys** [comment]
Hello, at the moment there is no way how to open overlay without using `<silent-box>` element. Sorry, I might add it later.
