### ISSUE TITLE
Problem using the component on Safari (iPad)

### ISSUE THREAD

**Issue by alexpvieira** [silencesys/silentbox#4]
Hello.

I was using this component on my SPA and it wasn't working on Safari (iPad version). There's a const that is being used on the component that doesn't work on Safari, showing a blank page.

After removig the component my page worked again, but i'll like to use it. There's any work around it?

**Comment by dotdevch** [comment]
Hi,
Vuejs SilentBox is very cool :) But the arrow left and right isn't there if I use the <silentbox-group>. I can slide next picture with the arrow keyboard. 

This is my code : 
````
<silentbox-group>
   <silentbox-item v-for="item in galerie" :key="item.ID" :src="item.sizes.large" :description="item.caption">
      <img :src="item.sizes.pomzed_thumb_630" >
   </silentbox-item>
</silentbox-group>
````

Thank's for reply

**Comment by silencesys** [comment]
Hello,

sorry for the stupid question, but do you have enabled javascript in your Safari? I am unable to debug it as I do not own iPad. 

Maybe if you could check the dev console if there is some error related to that const?
