### ISSUE TITLE
Just a little idea for your readme.md and your website - Method already accessible to open the lightbox

### ISSUE THREAD

**Issue by paulalbertdev** [silencesys/silentbox#45]
Hi ! I wanted to execute a method to open the lightbox so I dug into your lib a few seconds and found that the openOverlay method can totally do it with :
`<silent-box ref="gal" :gallery="gallery"></silent-box>`
and
`this.$refs.gal.openOverlay(this.gallery[0], 0)`
So I thought that you should maybe add this to the doc for other users of your library !
Cheers ;)

**Comment by silencesys** [comment]
Thank you! Readme was updated. I've added another method that someone might find useful. :)
