### ISSUE TITLE
IE11 breaking when silentbox esm packaged into app.js in Nuxt

### ISSUE THREAD

**Issue by maskott** [silencesys/silentbox#51]
I am having trouble with what seems to be a javascript error originating in silentbox.

I am using silentbox in a Nuxt based project and it works great, except in Internet Explorer 11. When I test in IE11, I see a javascript error in the console like so:

<img width="549" alt="Screen Shot 2021-02-26 at 12 37 08 AM" src="https://user-images.githubusercontent.com/4070380/109260112-8a763080-77cb-11eb-90b1-f373bd78408d.png">

When I inspect the referenced area in `app.js` I see:

<img width="1280" alt="Screen Shot 2021-02-26 at 12 43 35 AM" src="https://user-images.githubusercontent.com/4070380/109260181-ae397680-77cb-11eb-8667-076310164abd.png">

I was not sure if this was because of my Nuxt setup, so I made a very simple example to see if I still have the error. My code is located here https://github.com/maskott/silentbox-test and you can see the example live at https://truthful-dad.surge.sh/ (working fine in Chrome, but breaking in IE11).

Thank you for any light you may be able to shed on this issue!

**Comment by silencesys** [comment]
Hello, SilentBox is not meant to be used in IE11 as the official support ended in January 2016, sorry for that.
