### ISSUE TITLE
JSON.parse error when Vimeo request for thumbnail fails

### ISSUE THREAD

**Issue by mauricoder** [silencesys/silentbox#58]
When a request to Vimeo API for a thumbnail fails (ie a 404) the component doesn't handle the error, and it tries to parse the response anyways.

![image](https://user-images.githubusercontent.com/1232233/121409264-abf0c780-c937-11eb-9b6a-ff463ca68a8c.png)

Then there is a JSON.parse error

Still havent tried it in production, but in development that means that the whole page breaks.

There's a small fix to be done in item.js mixin when doing the XMLHttpRequest to handle this

I will gladly submit a PR for this if it's welcomed.

**Comment by silencesys** [comment]
Should be fixed in version 3 :)
