### ISSUE TITLE
Autoplay props not working in GogleChrome

### ISSUE THREAD

**Issue by VladKurluk** [silencesys/silentbox#8]
Hi! I use this plagin in my SPA. But i have problem with crossbrowser working it. Autoplay props in this plugin good working in the Firefox and not working in GoogleChrome. Maybe you can help me on this.

**Comment by silencesys** [comment]
Hello, 

it is quite long time since you posted this issue. I've checked it and I wasn't able to find any cross origin issue. It might have been due to a bug that was in Chrome. I'm closing the issue now, but if you'll still have problems with cross-origin, please let me know.
